{% set name = "lightgbm" %}
{% set version = "2.2.3" %}
{% set sha256 = "40354d21da6bfa73c7ada4d01b2e0b22eaae00f93e90bdaf3fc423020c273890" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"  # [not osx]
  script: 'export LDFLAGS="${LDFLAGS} -L$PREFIX/lib"; {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv'  # [osx]
  skip: True  # [win32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp       # [osx]
  host:
    - cmake
    - python
    - pip
    - setuptools
    - llvm-openmp       # [osx]
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - llvm-openmp       # [osx]

test:
  imports:
    - lightgbm

about:
  home: https://github.com/Microsoft/LightGBM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'LightGBM is a gradient boosting framework that uses tree based learning algorithms.'

  description: |
    A fast, distributed, high performance gradient boosting (GBDT, GBRT, GBM or MART) framework based on decision tree algorithms, used for ranking, classification and many other machine learning tasks.
  doc_url: http://lightgbm.readthedocs.io/en/latest/
  dev_url: https://github.com/Microsoft/LightGBM

extra:
  recipe-maintainers:
    - synapticarbors
    - aldanor
