travis:
  secure:
    BINSTAR_TOKEN: d/+YjntnZ6/arHOyOd9bDGO9RmJuT0CWwGVfh0R4tQgCtbCavvwNIT3ZTP5+TkVe7Ndj3266q0WaRhzKclTb3BQAaDV4Z7z7X6PJHSWnzO42HpOnNKwTRrtRP2LJzesn6B7aZzt8pIRwns7yYszAFyl/ArhZ+1CxOUszS80vwiZF9++w5LubNmd5hvLGcl9HFksG87GToYFekNJX2xOKDgMuFSXCMxaKcZ0ATAPAE0+jTfxSuJ3diD11+20WlyjHJBt42sGhskQPMFIJL6YQLXpPhN7mjc9TaZb/yHDJNB/4pewBwn+f2ZjrrY+dfIGJgMxpX8s2NsImLWc6q5BLUf10rfJ1bow2Jqs76Pgld+czBVND4iAXVcMgQqx/GxiT0thSOvHk9uf4O31jL3UPb8dwPOVXqROGzWqnu8z0HWy4WSYpxAnMCr3hpAdYc6zuYzdJyN+uuexPxkSxLlgzZ/CaTmChEldwxYGkx0gSY6tuYbWxsRl9TwU4HWxA717NkQO6mocvjjamG/FX26NDDuAb0OAkjEM7wbz91/emjMdoODwAm3Nm8YSQjvGoqGiB7Xm9JUjd1V7uFkLFkzL9cHwtnDFcUB+J3AMR7O//W+hSa+9NioGHP8noK0bombZTUK5Y0X4kF9aGyjd2r1jvHu5oe+LNUvD3VZmfsOiI8xc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
